### ISSUE TITLE
Create warm welcome to potential contributors, perhaps a "how to contribute guide"?

### ISSUE THREAD

**Issue by AdisPinjic** [Akvanvig/Discord-bot-py#8]
See title.

ALL CHANGES ARE TO BE PROMOTED TO #CAB (ME)

**Comment by audunsolemdal** [comment]
thumbs down.

Oh wait it's blocked.

**Comment by audunsolemdal** [comment]
nvm, you may close this issue.

**Comment by AdisPinjic** [comment]
NOT solved

KEEP calm and STAY open.

**Comment by MrOctopus** [comment]
please send ticket to project lead

**Comment by AdisPinjic** [comment]
UNSUBSCRIBED 

from further updates.

**Comment by AdisPinjic** [comment]
Changed title from "Create "how to contribute" guide so NOOBS doesn't dont have to ask STUPID questions on discord."

This was my final contribution.

Case closed.
